
import Head from 'next/head';
import Header from './src/Components/Header';
import Footer from './src/Components/Footer';
import Navbar from './src/Components/Navbar';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';


const RootLayout = ({ children }: any) => {
  return (
    <>
      <html>
        <Head>
          <title>E-commerce</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <Navbar />
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </>
  );
}

export default RootLayout;
